---
title: 'STAT 652: Statistical Learning and Prediction'
subtitle: 'Final Project - Predicting Flight Departure Delays'
author: "Padmanabhan Rajendrakumar - Student ID: 301360373"
output: pdf_document
---

```{r include = FALSE}
# R version 3.6.1
# packages used: tidyverse, dplyr, plyr, nycflights13, zoo, lubridate, psych, corrplot, gam , gbm, glmnet, xgboost, magrittr
# estimated running time: 10 minutes

knitr::opts_chunk$set(
  echo = FALSE,          
  warning = FALSE,       
  message = FALSE,       
  cache = FALSE,         
  fig.align = "center"   
)

```



```{r}
# Loading Libraries and Reading Input Data

library(tidyverse)       
library(dplyr)
library(nycflights13)
library(zoo)
library(lubridate)
library(plyr)
library(psych)
library(corrplot)

fltrain <- read_csv("Project652/fltrain.csv.gz")
fltest <- read_csv("Project652/fltest.csv.gz")

```

```{r, echo = FALSE}
# Data Preprocessing

##Adding some new features. Adding the `flag` feature based on 
##which the data will later be split into training and test set.

fltrain <- fltrain %>% mutate(season = factor(quarters(time_hour)), 
                              time_of_day = cut(hour,c(0,3,7,12,16,21,24), 
                                                labels = c("Late Night", 
                                                           "Early Morning", "Morning", 
                                                           "Afternoon","Evening", "Night"),
                                                right = FALSE),
                              delay = cut(dep_delay, c(-100, -1, 5, 60, 1500),
                                          labels = c("Early Departure", "No Delay", 
                                                     "Short Delay", "Long Delay"), 
                                          right = FALSE),
                              flag = "TR")

levels(fltrain$season) <- c("Winter","Spring","Summer","Fall")

```


```{r, echo = FALSE}
fltest <- fltest %>% mutate(season = factor(quarters(time_hour)), 
                              time_of_day = cut(hour,c(0,3,7,12,17,22,24), 
                                                labels = c("Late Night", "Early Morning", 
                                                           "Morning","Afternoon",
                                                           "Evening", "Night"), 
                                                right = FALSE),
                              delay = cut(dep_delay, 
                                          c(-100, -1, 5, 60, 1500), 
                                          labels = c("Early Departure", "No Delay", 
                                                     "Short Delay", "Long Delay"), 
                                          right = FALSE),
                              flag = "TE")

levels(fltest$season) <- c("Winter","Spring","Summer","Fall")

```



```{r}
## Merging Train and Test set for data-preprocessing. 
## Will be split later based on flag.

dataset <- merge(fltrain, fltest, all=TRUE)
```



```{r}
## Renaming some columns.
dataset <- dataset %>% 
  dplyr::rename(
    year = year.x,
    plane_manfactr_yr = year.y
    )

```



```{r}
## Sorting by date by each airport. This is done to impute NAs in weather related features. 
## The NAs are replaced with the most recent occurance.
dataset <- arrange(dataset, origin, year ,month,day,sched_dep_time)
dim(dataset)

```


```{r}
## Converting Chr features to Factors
flights_data <- as.data.frame(unclass(dataset))

```


```{r}
## Replacing weather related features with NA with the most recent non-NA prior to it.
flights_data$temp <- na.locf(flights_data$temp)
flights_data$dewp <- na.locf(flights_data$dewp)
flights_data$humid <- na.locf(flights_data$humid)
flights_data$wind_dir <- na.locf(flights_data$wind_dir)
flights_data$wind_speed <- na.locf(flights_data$wind_speed)
flights_data$precip <- na.locf(flights_data$precip)
flights_data$pressure <- na.locf(flights_data$pressure)
flights_data$visib <- na.locf(flights_data$visib)

```


```{r}
## Checking the % of NAs in each column
apply(flights_data, 2, function(col)sum(is.na(col))/length(col) * 100)

```


```{r}
## Rule of thumb 5% and removing features.
flights_data <- flights_data%>% 
  select(-wind_gust,-plane_manfactr_yr,-manufacturer,
         -engines, -speed, -engine, 
         -type, -model, -seats)

```


```{r}
## Complete case analysis. Removing any rows with at least one NA
flights_data <- na.omit(flights_data)
dim(flights_data)

```



```{r}
# Exploratory Data Analysis

## Multi Histogram on some numeric features
fl_temp <- flights_data %>% select(-year,-month,-day, -hour, -minute, -tz)
multi.hist(fl_temp[,sapply(fl_temp, is.numeric)])

```
Some heavily skewed features : dep_delay, arr_delay, precip, visib, alt


```{r}
## Corplot to analyse correlations
col_res = cor(fl_temp[, sapply(fl_temp, is.numeric)],
    use = "complete.obs", method = "pearson")
corrplot(col_res ,method="circle")
fl_temp <- NULL #deleting the temp dataframe

```


```{r}
## Response variable(dep_delay) Histogram
ggplot(data = flights_data, aes(x = dep_delay)) + geom_histogram(color="red", bins = 500)
boxplot(flights_data$dep_delay, xlab="Boxplot dep_delay")

```

The departure delays variable is highly right-skewed.

```{r}
range(flights_data$dep_delay)
fivenum(flights_data$dep_delay)
quantile(flights_data$dep_delay,probs = c(0, 0.01,0.05,0.1,0.25,.5,.75,.90,.95,.99, 1))
mean(flights_data$dep_delay >= 60)

```


```{r}
## Top 10 delays
flights_data%>% arrange(desc(dep_delay)) %>% head(10)

```



```{r}
## Summaries of departure delay by NYC airport
flights_data %>% group_by(origin) %>% 
  dplyr::summarize(n=n(),Median = median(dep_delay),
                   Third_Quartile = quantile(dep_delay,probs=.75), 
                   Max = max(dep_delay)) %>% 
  arrange(desc(Third_Quartile)) %>% head(10) 

```

```{r}
## Summaries of departure delay by season
flights_data %>% group_by(season) %>% 
  dplyr::summarize(n=n(),Median = median(dep_delay),
                   Third_Quartile = quantile(dep_delay,probs=.75), 
                   Max = max(dep_delay)) %>% 
  arrange(desc(Third_Quartile)) %>% head(10) 

```


```{r}
## Summaries of departure delay by time of day
flights_data %>% group_by(time_of_day) %>% 
  dplyr::summarize(n=n(),Median = median(dep_delay),
                   Third_Quartile = quantile(dep_delay,probs=.75), 
                   Max = max(dep_delay)) %>% 
  arrange(desc(Third_Quartile)) %>% head(10) 

```

```{r}
## Summaries of departure delay by NYC airport and season
flights_data %>% group_by(origin, season) %>% 
  dplyr::summarize(n=n(),Median = median(dep_delay),
                   Third_Quartile = quantile(dep_delay,probs=.75), 
                   Max = max(dep_delay)) %>% 
  arrange(desc(Third_Quartile)) %>% head(10) 

```

```{r}
## Summaries of departure delay by NYC airport and time of day
flights_data %>% group_by(origin, time_of_day) %>% 
  dplyr::summarize(n=n(),Median = median(dep_delay),
                   Third_Quartile = quantile(dep_delay,probs=.75), 
                   Max = max(dep_delay)) %>% 
  arrange(desc(Third_Quartile)) %>% head(10) 

```

```{r}
## Summaries of departure delay by airline (carrier)
flights_data %>% group_by(carrier) %>% 
  dplyr::summarize(n=n(),Median = median(dep_delay),
                   Third_Quartile = quantile(dep_delay,probs=.75), 
                   Max = max(dep_delay)) %>% 
  arrange(desc(Third_Quartile)) %>% head(10) 

```

```{r}
## Summaries of departure delay by origin and carrier
flights_data %>% group_by(origin,carrier) %>% 
  dplyr::summarize(n=n(),Median = median(dep_delay),
                   Third_Quartile = quantile(dep_delay,probs=.75), 
                   Max = max(dep_delay)) %>% 
  arrange(desc(Third_Quartile)) %>% head(10)

```

```{r}
## Summaries of departure delay by dest and carrier
flights_data %>% group_by(dest,carrier) %>% 
  dplyr::summarize(n=n(),Median = median(dep_delay),
                   Third_Quartile = quantile(dep_delay,probs=.75), 
                   Max = max(dep_delay)) %>% 
  arrange(desc(Third_Quartile)) %>% head(10) 

```

```{r}
## Summaries of departure delay by date
flights_data %>% group_by(month,day) %>% 
  dplyr::summarize(n=n(),Median = mean(dep_delay),Max = max(dep_delay)) %>%
  arrange(desc(Median)) %>% head(10)

```

```{r}
## Summaries of departure delay by precipitation
flights_data %>% mutate(haveprecip = factor(precip>0)) %>% group_by(haveprecip) %>% 
  dplyr::summarize(n=n(),Median = median(dep_delay),
                   Third_Quartile = quantile(dep_delay,probs=.75), 
                   Max = max(dep_delay)) %>% 
  arrange(desc(Median)) %>% head(10) 

```



```{r}
# Data wrangling

## Mapping `dep_delay` mapping to ranks
den <- nrow(flights_data)+1
flights_data <- flights_data %>% mutate(dep_delay = rank(dep_delay)/den)
ggplot(flights_data,aes(x=dep_delay)) + geom_histogram(binwidth=.01)

```



```{r}
## Removing features that are either heavily correlated with another variable 
## or represented by other vaiables.
library(lubridate)
flights_data <- flights_data %>% 
  mutate(dep_date = make_date(year,month,day)) %>% 
  select(-year,-month,-day,-dep_time,-arr_time,-arr_delay,
         -sched_arr_time,-air_time, -tz, 
         -dst, -tzone, -tailnum, -hour, 
         -minute, -time_hour, -name, -lat, -lon)

```


```{r,cache=TRUE}
## Relationships between departure delay and other quantitative predictors
ggplot(flights_data,aes(x=dep_date,y=dep_delay)) + 
  geom_point(alpha=.01) + geom_smooth()
ggplot(flights_data,aes(x=sched_dep_time,y=dep_delay)) + 
  geom_point(alpha=0.01) + geom_smooth()
ggplot(flights_data,aes(x=distance,y=dep_delay)) + 
  geom_point(alpha=0.01) + geom_smooth()
ggplot(flights_data,aes(x=temp,y=dep_delay)) + 
  geom_point(alpha=0.01) + geom_smooth()
ggplot(flights_data,aes(x=dewp,y=dep_delay)) + 
  geom_point(alpha=0.01) + geom_smooth()
ggplot(flights_data,aes(x=humid,y=dep_delay)) + 
  geom_point(alpha=0.01) + geom_smooth()
ggplot(flights_data,aes(x=wind_dir,y=dep_delay)) + 
  geom_point(alpha=0.01) + geom_smooth()
ggplot(flights_data,aes(x=wind_speed,y=dep_delay)) + 
  geom_point(alpha=0.01) + geom_smooth()
ggplot(flights_data,aes(x=precip,y=dep_delay)) + 
  geom_point(alpha=0.01) + geom_smooth()
ggplot(flights_data,aes(x=pressure,y=dep_delay)) + 
  geom_point(alpha=0.01) + geom_smooth()
ggplot(flights_data,aes(x=visib,y=dep_delay)) + 
  geom_point(alpha=0.01) + geom_smooth()
ggplot(flights_data,aes(x=alt,y=dep_delay)) + 
  geom_point(alpha=0.01) + geom_smooth()

```

```{r}
## Replace alt and dist with log(alt) and log(dist)
flights_data <- mutate(flights_data,
                       logdistance = log(distance)) %>% select(-distance)
flights_data <- mutate(flights_data,
                       logalt = log(alt)) %>% select(-alt)

```



```{r}
## Converting `dest` to numeric
dest_numeric <- as.numeric(flights_data$dest)
flights_data <- mutate(flights_data, dest = dest_numeric)

## Split dataset into train and test set based on `flag`
flights_train = flights_data %>% filter(flag == "TR") %>% 
  select(-flag, -logalt, -delay)
flights_test = flights_data %>% filter(flag == "TE") %>% 
  select(-flag, -logalt, -delay)

```



```{r}
# Learning methods
## data frame to save model metrics

models <- data.frame(Model=character(),
                 MSE=numeric(), 
                 RMSE=numeric(), 
                 stringsAsFactors=FALSE)
```


```{r,cache=TRUE}
# Learning methods

## Generalized Additive Model (GAM)
library(gam)
form <- formula(dep_delay ~ s(dep_date) + s(sched_dep_time) + carrier + 
                  origin + s(flight) + s(dest) + s(logdistance) + 
                  s(temp)  + s(humid) + s(wind_dir) + s(wind_speed) + 
                  s(precip) + s(pressure)+s(visib) +
                  season +time_of_day )
gam_fit <- gam(form, data=flights_train,family=gaussian) 
summary(gam_fit)
gam_pred <- predict(gam_fit,newdata=flights_test)
mse_gam <- mean((flights_test$dep_delay-gam_pred)^2)
print("GAM:")
cat("MSE:",mse_gam,"RMSE:",sqrt(mse_gam))
models[nrow(models) + 1,] = c("GAM", 
                              round(mse_gam, digits=5), 
                              round(sqrt(mse_gam), digits=5))

```


```{r,cache=TRUE}
## Gradient boosting (GBM)
library(gbm)
dep_date_numeric <- as.numeric(flights_train$dep_date)
dep_date_numeric <- dep_date_numeric - mean(dep_date_numeric)
fl_tr_tem <- mutate(flights_train,dep_date = dep_date_numeric)
gbm_fit <-gbm(dep_delay ~ . -dewp,data=fl_tr_tem , 
              distribution = "gaussian", bag.fraction = 0.5, 
              n.trees = 1000, interaction.depth =6, shrinkage = 0.1, 
              n.minobsinnode = 10)
summary(gbm_fit)
dep_date_numeric <- as.numeric(flights_test$dep_date)
dep_date_numeric <- dep_date_numeric - mean(dep_date_numeric)
fl_te_tem <- mutate(flights_test,dep_date = dep_date_numeric)
gbm_pred <- predict(gbm_fit,newdata=fl_te_tem ,n.trees = 1000)
mse_gbm <- mean((flights_test$dep_delay-gbm_pred)^2)
print("GBM:")
cat("MSE:",mse_gbm,"RMSE:",sqrt(mse_gbm))
models[nrow(models) + 1,] = c("GBM", 
                              round(mse_gbm, digits=5), 
                              round(sqrt(mse_gbm), digits=5))

```


```{r}
## Multiple Regression Model
lm_fit <- step(lm(dep_delay ~. , data = flights_train), direction ="both")
summary(lm_fit)
lm_pred <- predict(lm_fit,newdata=flights_test)
mse_lm <- mean((flights_test$dep_delay-lm_pred)^2)
print("Linear Model - Direction(Both)")
cat("MSE:",mse_lm,"RMSE:",sqrt(mse_lm))
models[nrow(models) + 1,] = c("LM", 
                              round(mse_lm, digits=5), 
                              round(sqrt(mse_lm), digits=5))

```

```{r}
## Model Matrix Creation
library(glmnet)

flights_train <- flights_train[, c(2,1,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18)]
flights_test <- flights_test[, c(2,1,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18)]

x = model.matrix(dep_delay~.-1, data=flights_train)
y = flights_train[,"dep_delay"]

x_te = model.matrix(dep_delay~.-1, data=flights_test)
y_te = flights_test[,"dep_delay"]

```


```{r}
## Ridge Regression Model
ridge_fit <- glmnet(x,y,alpha=0)
plot(ridge_fit,xvar="lambda",label=TRUE)
cv.ridge = cv.glmnet(x,y,alpha=0)
plot(cv.ridge)
ridge_pred <- predict(ridge_fit,newx=x_te)
mse_ridge <- mean((flights_test$dep_delay-ridge_pred)^2)
print("Ridge:")
cat("MSE:",mse_ridge,"RMSE:",sqrt(mse_ridge))
models[nrow(models) + 1,] = c("Ridge", 
                              round(mse_ridge, digits=5), round(sqrt(mse_ridge), digits=5))
ridge_pred <- predict(cv.ridge,newx=x_te)
mse_ridge <- mean((flights_test$dep_delay-ridge_pred)^2)
print("Ridge::CV")
cat("MSE:",mse_ridge,"RMSE:",sqrt(mse_ridge))
models[nrow(models) + 1,] = c("Ridge::CV", 
                              round(mse_ridge, digits=5), round(sqrt(mse_ridge), digits=5))

```

### Lasso Regression Model

```{r}
## Lasso Regression Model
lasso_fit <- glmnet(x,y,alpha=1)
plot(lasso_fit,xvar="lambda",label=TRUE)
cv.lasso = cv.glmnet(x,y,alpha=1)
plot(cv.lasso)
lasso_pred <- predict(lasso_fit,newx=x_te)
mse_lasso <- mean((flights_test$dep_delay-lasso_pred)^2)
print("Lasso::CV")
cat("MSE:",mse_lasso,"RMSE:",sqrt(mse_lasso))
models[nrow(models) + 1,] = c("Lasso", 
                              round(mse_lasso, digits=5), 
                              round(sqrt(mse_lasso), digits=5))
lasso_pred <- predict(cv.lasso,newx=x_te)
mse_lasso <- mean((flights_test$dep_delay-lasso_pred)^2)
print("Lasso::CV")
cat("MSE:",mse_lasso,"RMSE:",sqrt(mse_lasso))
models[nrow(models) + 1,] = c("Lasso::CV", 
                              round(mse_lasso, digits=5), 
                              round(sqrt(mse_lasso), digits=5))

```


### XGBoost

```{r}
## XGBoost
library(xgboost)
library(magrittr)

train_matrix = xgb.DMatrix(data = as.matrix(x), label=y)
test_matrix = xgb.DMatrix(data = as.matrix(x_te), label=y_te)
w<- list(train=train_matrix, test=test_matrix)

xgb_fit <- xgb.train(data=train_matrix, booster='gbtree',nrounds=2000, max_depth=5, eval_metric='rmse',eta=0.1, watchlist=w, early_stopping_rounds = 30 )

summary(xgb_fit)

xgb_pred <- predict(xgb_fit, newdata=x_te, class="response")
mse_xgb <- mean((flights_test$dep_delay-xgb_pred)^2)
print("XGBoost:")
cat("MSE:",mse_xgb,"RMSE:",sqrt(mse_xgb))
models[nrow(models) + 1,] = c("XGBoost", 
                              round(mse_xgb, digits=5), 
                              round(sqrt(mse_xgb), digits=5))
imp = xgb.importance(colnames(train_matrix), model=xgb_fit)
print(imp)

```

Comparison of models

```{r, eval=FALSE}
## Model Performance
print(models)

```